resources:
  - ../base

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: podinfo
    path: podinfo.yml
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: frontend
    path: frontend.yml
