name: Docker Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      release:
        description: "Release (e.g., v1.9.0)"
        required: true

permissions:
  contents: read

jobs:
  docker-release:
    runs-on: ubuntu-latest
    env:
      RELEASE: ${{ github.event.inputs.release || github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: Build Docker Images
        run: make VERSION=${RELEASE:1} DOCKER=coredns -f Makefile.docker release
      - name: Show Docker Images
        run: docker images
      - name: Docker login
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121  # v4.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Publish Docker Images
        run: make VERSION=${RELEASE:1} DOCKER=coredns -f Makefile.docker docker-push
        env:
          DOCKER_LOGIN: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
