name: 'Yamllint GitHub Actions'
on:
  - pull_request
permissions: read-all
jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          persist-credentials: false
      - name: 'Setup uv'
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b  # v8.1.0
      - name: 'Yamllint'
        run: |
          uvx --from 'yamllint==1.38.0' yamllint .
          echo "yamllint passed"
