resources:
  - github.com/stefanprodan/podinfo/kustomize?ref=6.7.0
  - frontend.yml
  - ns.yml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: podinfo
    path: patch-deployment.yml
