version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    labels: ["dependencies"]
    schedule:
      interval: "daily"
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    labels: ["dependencies"]
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    labels: ["area/ci", "dependencies"]
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "github.com/google/docsy"
      - dependency-name: "github.com/google/docsy/dependencies"
