version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  labels:
    - "release-note-none"
  open-pull-requests-limit: 10
  groups:
    kubernetes:
      patterns:
        - "k8s.io/*"
        - "sigs.k8s.io/*"
    opentelemetry:
      patterns:
        - "go.opentelemetry.io/*"
        - "github.com/uptrace/opentelemetry-go-extra/*"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
   interval: daily
  open-pull-requests-limit: 10
  labels:
   - "release-note-none"
