---
apiVersion: ceph.rook.io/v1
kind: CephBlockPoolRadosNamespace
metadata:
  name: namespace-a
  namespace: rook-ceph # namespace:cluster
spec:
  # The name of the RADOS namespace. If not set, the default is the name of the CR.
  # name: namespace-a
  # blockPoolName is the name of the CephBlockPool CR where the namespace will be created.
  blockPoolName: replicapool
  # ClusterID to be used for this RadosNamespace in the CSI configuration.
  # It must be unique among all Ceph clusters managed by Rook.
  # If not specified, the clusterID will be generated and can be found in the CR status.
  # clusterID: namespace-a
