spin_manifest_version = 2

[application]
name = "docs-fluxcd-website"
version = "0.1.0"
authors = ["Flux Community <kingdon@tuesdaystudios.com>"]
description = "fluxcd.io (testing)"

[application.trigger.http]
base = "/"

[[trigger.http]]
id = "trigger-app"
component = "app"
route = "/..."

[component.app]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [ { source = "../public", destination = "/" } ]
environment = { FALLBACK_PATH = "index.html" }
allowed_outbound_hosts = ["redis://*:*", "mysql://*:*", "postgres://*:*"]
