---
version: "2"
linters:
  default: none
  enable:
    - errcheck
    - govet
    - gosec
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: "QF1008:" # could remove embedded field "Connection" from selector (staticcheck)
      - linters:
          - staticcheck
        text: "QF1007:" # could merge conditional assignment into variable declaration (staticcheck)
      - linters:
          - staticcheck
        text: "QF1001:" # could apply De Morgan's law (staticcheck)
      - linters:
          - staticcheck
        text: "QF1006:" # could lift into loop condition (staticcheck)
      - linters:
          - staticcheck
        text: "Requeue is deprecated"
      - linters:
          - staticcheck
        text: "Use aws-sdk-go-v2" # aws-sdk-go v1 deprecated warning
formatters:
  enable:
    - gofmt
    - gofumpt
