---
run:
  build-tags:
    - apparmor
    - containers_image_ostree_stub
    # containers/image would use mtrmac/gpgme otherwise, which requires gpgme C headers
    - containers_image_openpgp
    - selinux
    - test
    # needs btrfs headers installed
    - exclude_graphdriver_btrfs
  concurrency: 6
  timeout: 10m
linters:
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - decorder
    - dogsled
    - dupl
    - dupword
    - durationcheck
    - errcheck
    - errchkjson
    - errorlint
    - exptostd
    - fatcontext
    - forcetypeassert
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - gofumpt
    - goheader
    - goimports
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosimple
    - gosmopolitan
    - govet
    - grouper
    - iface
    - importas
    - ineffassign
    - intrange
    - loggercheck
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilnesserr
    - nlreturn
    - noctx
    - nolintlint
    - nosprintfhostport
    - perfsprint
    - prealloc
    - promlinter
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tagalign
    - tenv
    - testableexamples
    - testifylint
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - wsl
    - zerologlint
    # - containedctx
    # - contextcheck
    # - cyclop
    # - depguard
    # - err113
    # - errname
    # - exhaustive
    # - exhaustruct
    # - forbidigo
    # - funlen
    # - gochecknoglobals
    # - gocognit
    # - godox
    # - gosec
    # - inamedparam
    # - interfacebloat
    # - ireturn
    # - lll
    # - maintidx
    # - mnd
    # - nestif
    # - nilerr
    # - nilnil
    # - nonamedreturns
    # - paralleltest
    # - predeclared
    # - tagliatelle
    # - testpackage
    # - thelper
    # - varnamelen
    # - wrapcheck
linters-settings:
  gci:
    sections:
      - standard
      - default
      - localmodule
  errcheck:
    check-type-assertions: true
    check-blank: true
  revive:
    rules:
      - name: argument-limit
        disabled: false
        arguments: [22]
  gocritic:
    enable-all: true
    disabled-checks:
      - filepathJoin
      - whyNoLint
  gocyclo:
    min-complexity: 177
  nakedret:
    max-func-lines: 15
  goconst:
    min-occurrences: 6
