name: docs-check
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docs-check:
    name: docs-check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: "1.22"

      - uses: actions/setup-python@39cd14951b08e74b54015e9e001cdefcf80e669f # v5.1.1
        with:
          python-version: 3.9

      - uses: DavidAnson/markdownlint-cli2-action@b4c9feab76d8025d1e83c653fa3990936df0e6c8 # v16.0.0
        with:
          globs: |
            Documentation/**/*.md
            !Documentation/Helm-Charts

      - name: Check helm-docs
        run: make check-helm-docs
      - name: Check docs
        run: make check-docs
      - name: Install mkdocs and dependencies
        run: cd build/release/ && make deps.docs

      - name: Check documentation for CRDs
        run: |
          make generate-docs-crds
          DIFF_ON_DOCS=$(git diff --ignore-matching-lines='on git commit')
          if [ ! -z "$DIFF_ON_DOCS" ]; then
          echo "Please run 'make generate-docs-crds' locally, commit the updated crds docs, and push the change"
          fi
          git diff --ignore-matching-lines='on git commit' --exit-code

      - name: Build documentation using mkdocs
        run: make docs-build
