name: docs-check
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*
  pull_request:
    branches:
      - master
      - release-*

# cancel the in-progress workflow when PR is refreshed.
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  docs-check:
    name: docs-check
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.23"

      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: 3.9

      - uses: DavidAnson/markdownlint-cli2-action@992badcdf24e3b8eb7e87ff9287fe931bcb00c6e # v20.0.0
        with:
          globs: |
            Documentation/**/*.md
            !Documentation/Helm-Charts

      - name: Check docs
        run: |
          make gen.docs
          tests/scripts/validate_modified_files.sh docs
      - name: Install mkdocs and dependencies
        run: cd build/release/ && make deps.docs

      - name: Check documentation for CRDs
        run: |
          make generate-docs-crds
          DIFF_ON_DOCS=$(git diff --ignore-matching-lines='on git commit')
          if [ ! -z "$DIFF_ON_DOCS" ]; then
          echo "Please run 'make generate-docs-crds' locally, commit the updated crds docs, and push the change"
          fi
          git diff --ignore-matching-lines='on git commit' --exit-code

      - name: Build documentation using mkdocs
        run: make docs-build
