name: Security scanning
on:
  push:
    tags:
      - v*
    branches:
      - master
      - release-*

permissions:
  contents: read

jobs:
  security:
    if: github.repository == 'rook/rook'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: run Snyk to check for code vulnerabilities
        uses: snyk/actions/golang@9213221444c2dc9e8b2502c1e857c26d851e84a7 # master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          GOFLAGS: "-buildvcs=false"
