name: tag reconciler
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
env:
  GO_VERSION: "1.23"
permissions:
  contents: read

jobs:
  tag-reconciler:
    permissions:
      actions: write
      contents: write
    if: github.ref == 'refs/heads/main' && github.repository == 'cri-o/cri-o'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make tag-reconciler
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
